import type { LucideIcon } from "lucide-react";
import {
  ArrowLeftRight,
  Braces,
  Cloud,
  Code,
  Code2,
  Coins,
  ContactRound,
  Database,
  Droplets,
  FileCode,
  FileText,
  Fingerprint,
  Hash,
  Image,
  KeyRound,
  Link,
  Lock,
  Mail,
  Palette,
  Scale,
  Sparkles,
  Square,
  Terminal,
  Wallet,
} from "lucide-react";

/** Lucide icons for each tool id — matches Untitled / Figma bundle. */
export const TOOL_LUCIDE_ICONS: Record<string, LucideIcon> = {
  "color-picker": Palette,
  "color-preview": Square,
  "json-validator": Database,
  "markdown-editor": FileText,
  "image-compressor": Image,
  "email-template": Mail,
  "password-generator": Lock,
  "api-tester": Cloud,
  "regex-builder": Terminal,
  "gradient-generator": Sparkles,
  "base64-encoder": Code,
  "url-encoder": Link,
  "jwt-tool": KeyRound,
  "hash-generator": Hash,
  "uuid-generator": Fingerprint,
  "format-converter": ArrowLeftRight,
  "unit-converter": Scale,
  "uniswap-sqrt": Droplets,
  "wei-human": Coins,
  "eth-address": ContactRound,
  "eth-wallet": Wallet,
  "function-selector": Code2,
  keccak256: Hash,
  "hex-bytes": FileCode,
  "abi-codec": Braces,
};

export function getToolLucideIcon(id: string): LucideIcon {
  return TOOL_LUCIDE_ICONS[id] ?? Code;
}
